version: '3.7'

services:
  backend:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"

    depends_on:
      - database
    networks:
      - db
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=firecode_test
      - DB_USER=admin
      - DB_PASS=admin
      - DJANGO_SUPERUSER_NICKNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin

  database:
    restart: always
    image: postgres:13-alpine
    container_name: database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=firecode_test
    networks:
      - db

networks:
  db:
    driver: bridge
